### ISSUE TITLE
Error Processing Library 

### ISSUE THREAD

**Issue by Josh5** [Josh5/unmanic#1]
Trying to process a part of my library. Getting this sort of error with different files. I have turned debugging on.

INFO:root:LibraryOptimiser - Processing files in '/library/'
INFO:root:LibraryOptimiser - Starting ScheduledTask
INFO:root:LibraryOptimiser - Starting EventProcessor
INFO:root:LibraryOptimiser - Running scheduled task
INFO:root:LibraryOptimiser - /library/
INFO:root:LibraryOptimiser - []
INFO:root:LibraryOptimiser - [
"Beauty and the Beast (2017).mkv",
"poster.jpg"
]
INFO:root:LibraryOptimiser - Checking file /library/Beauty and the Beast (2017)/Beauty and the Beast (2017).mkv
Traceback (most recent call last):
File "/optimiser", line 498, in 
main()
File "/optimiser", line 484, in main
wm.add_watch(LIBRARY_PATH, pyinotify.ALL_EVENTS, rec=True)
File "/usr/local/lib/python3.5/dist-packages/pyinotify-0.9.6-py3.5.egg/pyinotify.py", line 1916, in add_watch
File "/usr/local/lib/python3.5/dist-packages/pyinotify-0.9.6-py3.5.egg/pyinotify.py", line 1833, in __add_watch
File "/usr/local/lib/python3.5/dist-packages/pyinotify-0.9.6-py3.5.egg/pyinotify.py", line 153, in inotify_add_watch
File "/usr/local/lib/python3.5/dist-packages/pyinotify-0.9.6-py3.5.egg/pyinotify.py", line 246, in _inotify_add_watch
UnicodeEncodeError: 'ascii' codec can't encode characters in position 13-14: ordinal not in range(128)

**Comment by s1mpleman** [comment]
Yeah get this on my system too

**Comment by darrenjjeffries** [comment]
Also mine. Only Movies though

**Comment by NotExpectYet** [comment]
I ran this on a flat directory. So all movies in same folder and it worked fan, bar my other issue I raised with the ' character. When I run it on a folder with sub folders and the movie files in there I get the error above. 

Could that have anything to do with it?

**Comment by darrenjjeffries** [comment]
I am wondering if it is something to do with the large amount of folders at root level?

**Comment by NotExpectYet** [comment]
If I get chance ill do some more front end tests with that. Mine was certainly fine flat file, so something with folders. I ran it on a TV show one with 3 shows in a season each and that failed. So maybe just not traversing down the folder tree.

**Comment by Caedis** [comment]
Found the issue for me. WALL-E used a unicode character between the WALL and the E. Changed it to a dash and no errors.

Found the issue by editing the pyinotify to print the pathname before it was encoded in the original error.
