### ISSUE TITLE
More options for the encoder

### ISSUE THREAD

**Issue by DeBaard** [Josh5/unmanic#10]
It would be great to have more options to tweak the encoder settings if possible. It could be very granular at first to really tweak the output but it would also be great if there was a sort of 'easy' mode with a slider between small and large file-size output.

It could also be cool to include a 'preset' system so that users could swap out the best encoding options.

**Comment by scot5** [comment]
Simple choice of CRF would be a very easy method to implement

**Comment by Josh5** [comment]
I think I know where this is going. I believe this is possible after the changes that I am pushing with the dev-settings branch, but it will require some work. I'm going to put a pin in this one till a bit later on as this is not in the greatest demand right now.

**Comment by Wdavery** [comment]
Would it be possible to pass a specific command to ffmpeg? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Josh5** [comment]
It would not be so simple I think. You could add params. And I believe some encoders take additional params. But the problem is that all videos are not equal. The command would be different depending on what the source is, how many video/subtitle/audio streams are in it, etc.

**Comment by Josh5** [comment]
Added with Merge Request #129
