### ISSUE TITLE
Conversions are not moved into the target folders

### ISSUE THREAD

**Issue by tmertz** [Josh5/unmanic#100]
### Description

Conversions start, and files are created in the cache, but are never moved from cache to the origin directory. Also never show up in Completed Tasks list.  

### Steps to Reproduce

1. Start docker container

**Expected behavior:** 

I'd expect completed conversions moved into origin directory and original files deleted.

**Actual behaviour:** 

Conversions remain in the origin directory. Original files are untouched. 

**Reproduces how often:** 

100%

### Versions

The version can be found at the footer of the WebUI. Also, please include the OS details and what version you are running
(e.g. `cat /etc/os-release`).

v0.0.1-beta7~0be090f 
Running via Docker on Unraid.

### Installation Method Used

Docker

### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

**Comment by wjbeckett** [comment]
I had this same issue. 
I fixed it by adding :rw to the end of my volumes line to ensure the container had readwrite access to the media locations.

**Comment by tmertz** [comment]
I am running it on Unraid, so I'll have to dig around on how to add that variable. :D

**Comment by wjbeckett** [comment]
@tmertz, it's more about permissions really. Ensuring the container user has the right permissions to write to the destination

**Comment by tmertz** [comment]
No no, I get that. :D

**Comment by jfroebe** [comment]
An error message would be helpful in the output on the web page.  The documentation should be updated to reflect the re volume option imo

**Comment by randomparity** [comment]
I'm seeing a similar issue.  Running with Docker on Ubuntu 19.10, library is NFS mounted:

```
sysadmin@Beast:~$ mount | grep Series
media:/zpool0/media/series on /home/sysadmin/Series type nfs4 (rw,noatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,acregmin=1800,acregmax=1800,acdirmin=1800,acdirmax=1800,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=192.168.2.140,local_lock=none,addr=192.168.2.2)
```

Mount point has full read/write permission for the logged-in user:

```
sysadmin@Beast:~$ id -u
1000
sysadmin@Beast:~$ id -g
1000
sysadmin@Beast:~$ ls -alh | grep Series
drwxrwxr-x  6 sysadmin sysadmin    6 Mar  4 09:42  Series
```

Docker container was started with the correct PUID/PGID values:

```
sysadmin@Beast: ~$  docker run -d --name unmanic --network=host -e PUID:1000 -e PGID:1000 -v /home/sysadmin/.config/docker/unmanic:/config -v /home/sysadmin/Series:/library  josh5/unmanic:latest
```
I can enter the Docker container and create/delete files on the NFS mount:

```
sysadmin@Beast:~$ docker exec -it unmanic /bin/bash
root@Beast:/$ su docker
docker@Beast:/$ cd /library
docker@Beast:/library$ ls -alh
total 79K
drwxrwxr-x   6 docker users   6 Mar  4 17:52 .
drwxr-xr-x  24 root   root   26 Mar  4 04:34 ..
drwxrwxr-x 214 docker users 214 Feb 24 05:57 .deleted
drwx-w----   2 docker users   2 Apr 17  2019 .recycle
drwxrwxr-x 231 docker users 232 Feb  9 21:31 library
drwxrwxr-x   2 docker users   2 Sep  9  2018 scripts
docker@Beast:/library$ touch test
docker@Beast:/library$ ls -alh
total 80K
drwxrwxr-x   6 docker users   7 Mar  4 17:52 .
drwxr-xr-x  24 root   root   26 Mar  4 04:34 ..
drwxrwxr-x 214 docker users 214 Feb 24 05:57 .deleted
drwx-w----   2 docker users   2 Apr 17  2019 .recycle
drwxrwxr-x 231 docker users 232 Feb  9 21:31 library
drwxrwxr-x   2 docker users   2 Sep  9  2018 scripts
-rw-rw-rw-   1 docker users   0 Mar  4 17:52 test
```

And yet, there's a backlog of files that have been converted but not copied back to the library nor shown in the History tab. Is it still a permission problem?

**Comment by mattboy9921** [comment]
I seem to be experiencing the same thing. I've checked all my permissions but both the user the container runs with and the container itself can read and write to all the applicable directories. 

My temporary directory for Unmanic has hundreds of folders in it, but the container only sees about 16 of them. I've even tried completely wiping all traces of Unmanic and reconfiguring it but I get the same issue. No files appear in the completed list.

**Comment by baldfox** [comment]
> My temporary directory for Unmanic has hundreds of folders in it, but the container only sees about 16 of them. I've even tried completely wiping all traces of Unmanic and reconfiguring it but I get the same issue. No files appear in the completed list.

I am running into the exact same issues. I can set up the configuration but I cannot see current jobs or past jobs. No statistics at all.

**Comment by mattboy9921** [comment]
What I've done is set up a test instance of Unmanic that has access to just one TV show worth of unconverted files. I've got debugging on in the Unmanic settings. From there, I grab the terminal of the Docker container and view the log at `/config/.unmanic/logs/unmanic.log`. 

It appears to be doing the work. The VM I am runnning the container inside of sees CPU utilization. I see the line `Successfully converted file 'something.mkv'` I see one example where it says `Moving file sometempfile.mkv --> actualfilelocation.mkv` but when examining the file, it is still H264. Other than that one example of moving the file, I see that for no other file that has been "successfully converted".

Could there be some issue where the file is taking too long to copy or times out and causes no other file to copy? 

(To confirm, from within the Docker container, I can create and delete files from the library folder without issue so I do not believe this to be a permissions issue)

**Comment by Josh5** [comment]
This was a permission issue.
Fixed the README.md documentation (thanks) for the docker run command. See commit d73f3d6 

Closing issue as no further work is required.
