### ISSUE TITLE
TZ not applying properly 

### ISSUE THREAD

**Issue by dwtaylornz** [Josh5/unmanic#115]
### Description

TZ seems to be out by 12 hours 
(i.e. at 2pm in the afternoon time in history shows 02:00 when i'd expect to see 14:00) 

### Steps to Reproduce

1. [First Step]
Pass environment variable TZ=Pacific/Auckland on execution 

**Expected behavior:** [What you expect to happen]

Would expect to see proper 24hr format

**Actual behaviour:** [What actually happens]

History start and finish time appear to be 12hrs behind. 

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% 

### Versions

Version - 0.0.1-beta7+1a6d561

### Installation Method Used

Docker

**Comment by Josh5** [comment]
This is no longer an issue since switcing to the lsiobase/ubuntu base image for docker in commit d2e95f43d271da96c94575242654432bf8b6c1d4
