### ISSUE TITLE
Files failing to convert

### ISSUE THREAD

**Issue by IrishTechnician** [Josh5/unmanic#122]
I have noticed that while smaller files convert fine, larger files do not. 

It looks like the issue lies with files that have subtitles maybe? I have tried resetting the database to no avail and don't want to lose the subs embedded in the files. The installation is via Docker on unraid. 

Below is the debug output from a file:

[SingleFileLog.txt](https://github.com/Josh5/unmanic/files/5066630/SingleFileLog.txt)

The error:
[matroska,webm @ 0x5655577690c0] Could not find codec parameters for stream 3 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options

with stream 3 being: Stream #0:3(eng): Subtitle: hdmv_pgs_subtitle

Is there a way for me to increase the above values from within the docker container?

**Comment by Josh5** [comment]
There is now an option to do so under the advanced tab in the settings.
Here you can add additional FFMPEG options to the command. See how that goes.

Closing issue as no work is required.
