### ISSUE TITLE
VAAPI &other hardware transcoding & Docker support

### ISSUE THREAD

**Issue by Protektor-Desura** [Josh5/unmanic#124]
I see you are using Linuxserver as your core for the docker. It would be nice to see it support VAAPI and AMF hardware transcoding for AMD CPUs since they are way cheaper than Nvidia and don't have an artificial limit of how many streams you can do at once.

VAAPI should be a snap to add. Just add the ffmpeg VAAPI options for encoding H.264 and HEVC and obviously compile in VAAPI support in ffmpeg:
https://trac.ffmpeg.org/wiki/Hardware/VAAPI
```
h264_vaapi 
hevc_vaapi
```

Then for docker all you need to do is add these lines to your Dockerfile that create the docker for VAAPI support. Basically you need Mesa 20.1 or higher installed inside the docker and for AMD they will need amdgpu-pro installed on the host OS to do HEVC transcoding.

```
apt-get update && apt-get upgrade -y
apt-get install -y gpg
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F63F0F2B90935439
echo "deb http://ppa.launchpad.net/kisak/kisak-mesa/ubuntu bionic main" > /etc/apt/sources.list.d/kisak-ubuntu-kisak-mesa-bionic.list
apt-get update && apt-get upgrade -y
```

Users also need the following line added when the user creates their docker:
``` 
--device=/dev/dri `#optional VAAPI & Intel Quick Sync support` \
```
You just need to compile in AMF support in to ffmpeg to add hardware AMF support.
https://www.ffmpeg.org/general.html#AMD-AMF_002fVCE

Also you need to add to docker docs that users need to add:
--runtime=nvidia
-e NVIDIA_VISIBLE_DEVICES=all

Nvidia users will also need to install the nvidia docker toolkit to get Nvidia support in docker as well.
https://github.com/NVIDIA/nvidia-docker

If you want to support Intel QuickSync hardware support. Again you need Mesa 20.1 or higher in docker and then compile FFMPEG with Intel Quick Sync support.
https://trac.ffmpeg.org/wiki/Hardware/QuickSync

Might be nice to see webm containers and VP8 and VP9 supported as well. Since most browsers and android devices support VP8/VP9 as well. Yes there is also hardware transcoding available for V8 & VP9. Just need to compile ffmpeg to support it.
https://caniuse.com/?search=vp8
https://caniuse.com/?search=vp9
https://caniuse.com/?search=webm
https://developer.android.com/guide/topics/media/media-formats

**Comment by Protektor-Desura** [comment]
Biggest issue with supporting all this is probably the documentation and basically compiling ffmpeg with all the options available.

**Comment by Josh5** [comment]
I do not have the ability to develop AMF HW acceleration as I do not have the hardware available to do so. This will need to be done by someone else.
For now, NVIDIA and Intel support has now been added...
