### ISSUE TITLE
Unraid filling up docker image

### ISSUE THREAD

**Issue by Jadiction** [Josh5/unmanic#152]
### Description

While running Unmanic over time, it fills my docker image file. It was once 25 GB, but I increased it to 100 GB weeks ago. Recently my docker image hit 100%, so I looked into it. With a `docker ps --size`:
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS                 PORTS                                                                                                                                                NAMES                   SIZE

492efbd03106        josh5/unmanic                      "/init"                  3 weeks ago         Up 17 hours            0.0.0.0:8888->8888/tcp                                                                                                                               Unmanic                 95.9GB (virtual 96.5GB)

Unsure what is causing this as I cannot start the Unmanic docker without an error. I'll have to delete it.
To rule out any possibilities of it being the log DB being stored in the docker, it's assigned to a share & is only ~5GB.

The version can be found at the footer of the WebUI. Also, please include the OS details and what version you are running
(e.g. `cat /etc/os-release`).
Unraid 6.8.3

NAME=Slackware
VERSION="14.2"
ID=slackware
VERSION_ID=14.2
PRETTY_NAME="Slackware 14.2 x86_64 (post 14.2 -current)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:slackware:slackware_linux:14.2"
HOME_URL="http://slackware.com/"
SUPPORT_URL="http://www.linuxquestions.org/questions/slackware-14/"
BUG_REPORT_URL="http://www.linuxquestions.org/questions/slackware-14/"
VERSION_CODENAME=current

### Installation Method Used

Manually installed and run or run through Docker?

Docker

**Comment by Josh5** [comment]
Can you please post your docker config. Screenshots of your unraid docker config page will do.

**Comment by Jadiction** [comment]
@Josh5 

![](https://image.prntscr.com/image/HkOO2J2PRdWf1iL4Nj2pgA.png)

**Comment by Josh5** [comment]
Where is your cache configured in unmanic's settings? You docker settings is missing the path for the /tmp/unmanic mount.

**Comment by Jadiction** [comment]
Ah, you mean the `Encoding Cache Directory`? I assume the cache is what's taking the storage then. Specifying that to a share should fix it, yeah?

**Comment by Josh5** [comment]
Yes. That's correct. The cache is temporary storage. Try setting that and get back to me if you notice that either the mount continues to fill with temp files or the container continues to grow.

**Comment by Jadiction** [comment]
Gotcha, got it set up properly now. I'm sure this will fix the issue, so I'll close the issue and open up if anything else happens.

Thanks!
