### ISSUE TITLE
Manipulation of our "Pending Tasks" list

### ISSUE THREAD

**Issue by Josh5** [Josh5/unmanic#18]
1.  Allow ignoring files in the "Pending Tasks" list 
    If there is a file that does not need to be converted, we should be able to remove it from our list.
2. Allow setting order of the queue
    We may have a particular file that needs to be done first

**Comment by PaulHol** [comment]
An option to randomise the pending tasks list could be handy. Currently I'm getting a single disk being worked hard for a very long time as all episodes of a season are kept together on the one disk.
