### ISSUE TITLE
Messed up Audio Streams

### ISSUE THREAD

**Issue by jaddel** [Josh5/unmanic#30]
Hi here is quick description of the problem: 

1. My library is dual language
2. After transcoding it looks like this: <img width="316" alt="Bildschirmfoto 2019-04-25 um 14 29 22" src="https://user-images.githubusercontent.com/46263124/56735732-91166580-6766-11e9-95d8-2fd727c8d71d.png">
3. Any mistakes i'm doing or is it a bug in unmanic? 

thx

**Comment by Josh5** [comment]
So I can close this issue?

**Comment by jaddel** [comment]
I’ll give it a try straight away and repost as soon the transcoding is done.

**Comment by jaddel** [comment]
I’ve just seen, there has been no update since my last try, so presume nothing has changed about audio conversion.
Does anybody else has this problem?

**Comment by jaddel** [comment]
I just gave it a new try with 0.0.1-beta4~d54ee24:

These are my results (media info VLC Player): 

<img width="203" alt="Bildschirmfoto 2019-05-09 um 11 18 46" src="https://user-images.githubusercontent.com/46263124/57443630-c8007700-724e-11e9-9747-b431d42442c2.png">
<img width="509" alt="Bildschirmfoto 2019-05-09 um 11 18 39" src="https://user-images.githubusercontent.com/46263124/57443632-c8007700-724e-11e9-9237-89841b72b940.png">
<img width="512" alt="Bildschirmfoto 2019-05-09 um 11 18 30" src="https://user-images.githubusercontent.com/46263124/57443633-c8990d80-724e-11e9-9054-8d441d259bc1.png">

FYI:

If i got it right audio stream 1 and 4 are the multichannel streams. What irritates me is that stream 1 has a clear info about channels (Kanäle), while in stream 4 this information is missing.

**Comment by Josh5** [comment]
Can you send me a sample video?
I have push a log of changes to ffmpeg over the past month. It is worth now taking a look into this issue.

**Comment by Josh5** [comment]
Not enough information for me to continue
