### ISSUE TITLE
FFMPEG errors on certain files that keeps them from being processed

### ISSUE THREAD

**Issue by Drawmonster** [Josh5/unmanic#32]
### Description

Certain files in library error out and can't be processed. Unmanic creates a temporary file that has a size of zero kilobytes and then skips files. Manually deleting files and replacing them with different releases sometimes allows file to be processed. So Unmanic is having issues with certain file types.

### Steps to Reproduce

1. Start Unmanic
2. Library is scanned and workers pick up jobs for files in question
3. Unmanic creates temp file and tries to process, but then skips files and shows errors in log

**Expected behavior:** Unmanic should process all library files

**Actual behaviour:** Unmanic has errors and skips certain video files

**Reproduces how often:** Happens 100% of time with same files

### Versions

Happens in "Latest" and "dev-jobpipeline" versions in Docker

### Installation Method Used

Docker

### Additional Information

Log showing errors:
https://pastebin.com/8GiEWeY1

**Comment by Josh5** [comment]
Looks like this is an issue with ffmpeg filling the packet queue before it has been able to read one from each stream in the file. 
From the docs (https://ffmpeg.org/ffmpeg.html):
> When transcoding audio and/or video streams, ffmpeg will not begin writing into the output until it has one packet for each such stream.

Fixed with commit e0ce97e
