### ISSUE TITLE
Possibility to Remux

### ISSUE THREAD

**Issue by MrMeeb** [Josh5/unmanic#36]
Would be nice to be able to change the container of the file without re-encoding everything.

It appears that the current behavior when changing a container is to re-encode the entire file (at least judging by the speed and CPU utilisation), even if everything about it already matches the desired settings. My understanding of this would mean a loss in quality, due to double encoding. Instead, it could simply be copying any codec that already matches the desired settings into the new container, and only changing those codecs that don't match the desired outcome (probably more likely to apply to the audio codec), if any.

This would mean that, for people simply wanting to change containers for compatibility, the entire process would happen much faster, be less intense on the system, and not degrade the quality of their files.

I think this is going to be an awesome tool, especially for people that don't feel like writing ffmpeg scripts, like myself! Just thought I'd offer my two cents 😄

**Comment by UnR34L** [comment]
+1 for this.

A lot of people would use this for better compatibility with applications like Plex and Emby. Sometimes all you need is a compatible audio codec.

Ideal scenario, set the wanted video/audio codec and container in settings. Re-encode only the stuff that doesn't match.
