### ISSUE TITLE
[Feature Request] Auto merge subtitles

### ISSUE THREAD

**Issue by Nonobis** [Josh5/unmanic#41]
Hello,

Very good soft.... but would be very nice to have an option for auto merging of video & subtitle ...

Ex :

"XXX".mp4 / mkv / avi  & "XXX.fr".srt 
=> if you could add an auto to merge video with subtitle with same name and use language code for mkv track and then delete srt file ...

**Comment by Josh5** [comment]
This is not something that I want to undertake. Feel free to submit a PR if you want to do it yourself

**Comment by timdonovanuk** [comment]
Is it bad practice to do this? Is this not a commonly requested thing?
