### ISSUE TITLE
Completed tasks list not in chronological order.

### ISSUE THREAD

**Issue by HenkaN94** [Josh5/unmanic#49]
### Description
Most times a job finishes and gets put into the completed tasks list it get sorted by time of completion, however sometimes it will put new completed jobs in the bottom of the list kind of like this.
This applies to both the dashboard list and the list with statistics.

Completed just now
Completed 3 hours ago.
Completed 5 hours ago.
Completed 2 hours ago.
Completed 1 hour ago.

### Versions
Version - 0.0.1-beta4~aad4ffd 

### Installation Method Used
Both unRaid docker and manual install.

### Additional Information
Worth to add is that i have ~200+ finished jobs and i am unsure how it looks with very few finished jobs.
This is also annoying if you want to double check statistics or something after jobs are done, if you don't pay attention and scroll down you might believe the records are gone.

**Comment by Josh5** [comment]
Fixed in commit bf9d8d426a412e21c802e6691cf11ef3f31f1b33
