### ISSUE TITLE
Long filenames will push buttons out of the box

### ISSUE THREAD

**Issue by HenkaN94** [Josh5/unmanic#51]
### Description

Having long filenames and/or a low resolution monitor will push the "Success" icon and "View details" button out of the box.

### Versions

Version - 0.0.1-beta4~aad4ffd 

### Installation Method Used

Both unRaid docker and manual install.

### Additional Information

Because of focus issues sometimes it's hard to do middle mouse down and scroll to the right, however the scrollbar thing is visible if you go down to the bottom of the page.
My personal suggestion is that you either always show the scrollbar on the bottom or lock the button to the right and always force the text to split up on multiple lines.

**Comment by Josh5** [comment]
Fixed in commit bf9d8d426a412e21c802e6691cf11ef3f31f1b33
