### ISSUE TITLE
Pull From Official Docker Containers

### ISSUE THREAD

**Issue by Dr-Crow** [Josh5/unmanic#55]
### Description

We should be pulling from official docker containers not custom containers you made. This will accomplish a couple things:

- Its best practice
- Allows for users to easily port and expand the base containers, aka add support for Debian, Ubuntu, etc
- Mitigate security issues to upstream containers, instead of relying on you to update your containers with security patches 

### Additional Information

I am fine with just pulling from `Alpine` like you have now, but directly from the official image not your custom image.

**Comment by Josh5** [comment]
Agreed. I think for this project, it has evolved beyond needing my docker image. Rebasing it to use an official base image will simplify things moving forward. We should start with official Alpine.

**Comment by Josh5** [comment]
Done
