### ISSUE TITLE
Develop a CI/CD Pipeline for Releases and Tests

### ISSUE THREAD

**Issue by Dr-Crow** [Josh5/unmanic#56]
### Description

Let's use something like [Travis](https://travis-ci.org/) to build Docker images, run test coverage on your python package and manage releases. 

Travis is free and user simple to implement, since you just add 1 file to your repo. 

With implementing Travis, when you push, your code will automatically be run against your tests which will give you automatic feedback on your commits. 

Additionally, you can configure to build a Docker image and/or publish a release if it passes all your test. 

### Additional Information

I am pretty familiar with Travis, so if you would like help implementing this let me know!

**Comment by Josh5** [comment]
The project is already in a CI pipeline using [TeamCity](https://www.jetbrains.com/teamcity/). I'm currently happy with this pipeline for now and am not interested in switching to anything else at this time.
