### ISSUE TITLE
Database Type and Driver

### ISSUE THREAD

**Issue by Dr-Crow** [Josh5/unmanic#57]
### Description

I saw you were implementing a database on your branch, `dev-settings`, from #43. I think in addition to adding just statics, we should talk about the database layout/design.

I notice you seem to be adding setting into the database as well?

Additionally, I think we should rethink the database driver in favor of something that is a little more popular and well documented, instead of using `peewee`. The "golden" standard for ORMs is [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

While I don't mind using SQLite, I think if we are this early in development we should use a more stable/heavy duty database. This would avoid having to port it later down the line. I would suggest something like PostgresSQL.

Any thoughts on what I said above, @Apocrathia, you seemed to have an interest/good understand of databases from what your said in the other issue.

### Additional Information

I am happy to help in designing and implementing a database. I work a lot with databases and python, so feel free to ask me any questions you have!

**Comment by Josh5** [comment]
I'm happy to discuss DB layout and design. What sort of things did you have in mind?
I'm starting with a "settings" table and then, once that is implemented I will move onto adding all logging for the stats and reporting. Beyond that I am unsure of anything else that may be required for this application. It is my intent not to let it bloat out to a complicated application.
With that last point in mind, I've chosen to support SQLite as it requires no effort on the user's part for maintaining a server. peewee will be used in such a way that it will be possible for a user to use something like PostgreSQL if they want to set all that up. I cannot understand myself who's library could actually get so big that they would come close to the limits of SQLite requiring the effort of using PostgreSQL, but I may be wrong.
I have chosen peewee for its simplicity. When I look at SQLAlchemy, it comes across to me like the tool that does everything. This is perfect for a website or something that requires a lot of features, but that is not what Unmanic will ever be. Unmanic's #1 primary goal will always be simplicity. I will not allow the application to bloat to the point where an average person cannot use it. This being said, if you can give me a reason other than "SQLAlchemy is familiar", "I've used it before" or "every one uses it", I could still be persuaded to make the change from peewee before finishing that branch. I'm not against hearing other peoples ideas.

I also have a few years of experience with implementing databases. I probably wont have any questions, but if you let me know specifically what ideas you had, i'm all ears...
