### ISSUE TITLE
Reworking of the Tests and Setting Up a Sustainable Test Environment

### ISSUE THREAD

**Issue by Dr-Crow** [Josh5/unmanic#59]
### Description

I wanted to talk about reworking of the tests for this project. I noticed you are using PyTest or at least have it in the `requirements.txt`. I love PyTest and think its a good testing framework, this fits nicely into #56. 

When setting up a test environment we should be keeping that code separate from our main code.  For example I noticed in `ffmpeg.py` you have a class for testing out the functionality of fmpeg. This class should be taken out of this python file and brought into its own file under the `tests` directory. 

In the `tests` directory there seems to be a lot of bash. It looks like you are trying to get files in place to test if the transcoding works. That is a pretty good idea, but I think it a redesign of it would be a good idea to fit into the CI/CD pipeline. I am not sure what the best solution is. Maybe have a docker container with the required media to test? Then launch that in our CI/CD pipeline? 

I am not sure, but I know testing is important. I think taking time to discuss the test environment setup will benefit this project greatly.

**Comment by Josh5** [comment]
Everything that you have mentioned here is already implemented. Yes these scripts are used with TeamCity to pull in a range of test video files to test the ffmpeg.py file. 

I think you are right, it would be nice to separate the files. Originally, Unmanic was designed as a thrown together CL application. The tests were added in their files to reduce dev time etc. No that the application has evolved, it would be nice to separate them from production code.
Go ahead, make it happen. :+1:

**Comment by Dr-Crow** [comment]
You mentioned you are using Team City, I am not familiar with it, but I do love the Jet Brain Products. 

Does Team City offer so public UI where I can see the tests you've ran?

Also, does it have the ability to build for multiple architectures? I just quickly looked at it.

**Comment by Josh5** [comment]
TeamCity is working fine for now. I will look at public facing UI if code contributions pick up
