### ISSUE TITLE
Road map and General Discussion on Project's Direction

### ISSUE THREAD

**Issue by Dr-Crow** [Josh5/unmanic#60]
I wanted to open this issue to talk about your plans/ideas going forward with the project. As in, what do you think you need help on? What are some features you want to see implemented, etc. 

I open some issues regarding some restructuring of the project and general best practices that should/hopefully will be adopted. 

Here they are:

- Simple delete of the `.idea` folder #54
- Pulling from Official Docker Images/Best practices with Docker #55
- Automate building, test, and releases with CI/CD Pipelines #56 
- Figure out plans for database going forwarded #57 
- Framework of the project going forward #58 
- Setting up a good test environment #59 
- Use one of the FFMPEG python packages instead writing our own wrapper #61 

I wish Github supported Epics in there non-enterprise version :(

**Comment by Josh5** [comment]
Awesome, Glad that you are wanting to come aboard and assist with development.
I will write some notes on the opened issues and the come back to this one.

**Comment by Josh5** [comment]
I've written some notes on the issues that you have raised. I do not agree with everything, but I think you are heading in the right direction with most things

**Comment by Josh5** [comment]
No further discussion. Closing issue
