### ISSUE TITLE
Movies encoding not working

### ISSUE THREAD

**Issue by letrain02** [Josh5/unmanic#64]
It's been working great until yesterday. It starts encoding a movie and gets to 2-3% then just disappears and starts on the next one. No failures listed. No completion. And the movie disappears from the pending list until they are all gone. When I reboot they show up and it starts all over again. Tv shows work fine.

**Comment by Josh5** [comment]
I'm adding improvements to logging at the moment. Once that is done, I'll get you to retest so you can add the logs here.

**Comment by Josh5** [comment]
Can you please retest with debugging enabled. I have added full FFMPEG command logging support. You can view it in the history log of that failed task.
Eg:
![image](https://user-images.githubusercontent.com/8370197/66374416-6fa0f180-ea07-11e9-823f-8b67b44a1654.png)

**Comment by Josh5** [comment]
Not enough information. Closing
