### ISSUE TITLE
Give GUI browser tab a more useful name

### ISSUE THREAD

**Issue by itimpi** [Josh5/unmanic#68]
At the moment when I fire up the Unmanic GUI running in a docker container from a browser running on another machine the browser tab gets labelled as ‘Home’.   Is it possible to give it a more meaningful  name?   Simply calling it ‘Unmanic’ would be an improvement, but I would suggest Ideally this could be a name you could configure in Settings.

**Comment by Josh5** [comment]
This will not be a configurable thing. But I'll look into improvements.
