### ISSUE TITLE
[Features] Add support for Gpu / Intel QuickSync

### ISSUE THREAD

**Issue by Nonobis** [Josh5/unmanic#76]
I don't know if it's possible for unmanic, but could you add support for gpu / Intel QuickSync sync ?
Ffmpeg full version support this

Thanks

**Comment by Josh5** [comment]
This will be possible along side the Nvidia HW encoding

**Comment by Nonobis** [comment]
Thanks :)

**Comment by Josh5** [comment]
Completed
