### ISSUE TITLE
Append / rename file name with x265 tag for radarr 

### ISSUE THREAD

**Issue by jpaige5408** [Josh5/unmanic#78]
Feature request: Post-Process file rename for movies. Radarr recommends movie name syntax of:

{Movie Title} ({Release Year}) - {[EDITION TAGS]}{[QUALITY FULL]}{[MEDIAINFO AUDIOCODEC}{ MEDIAINFO AUDIOCHANNELS]}{[MEDIAINFO VIDEOCODEC]}{-RELEASE GROUP}

The Movie Title (2010) - [ULTIMATE EXTENDED EDITION][BLURAY-1080P PROPER][DTS 5.1][X264]-EVOLVE

Currently the values for [MEDIAINFO AUDIOCODEC], [MEDIAINFO AUDIOCHANNELS], and [MEDIAINFO VIDEOCODEC] in each file name must be *manually changed after conversion. Would be a huge step toward full automation for unmanic to automatically update movie file names along the lines of x264 —> x265, DTS 5.1 —> ST 2.0 (if applicable), etc.

**Comment by Josh5** [comment]
This is out of the scope of what Unmanic is trying to achieve.
That being said, it is my intention to add the ability to execute post-processing scripts on completed video files. This will allow people to write bash/python/whatever scripts to carry out custom tasks such as what you describe here once a conversion task is complete.
That will be done against the already open issue 31. So please watch that one for progress.

Cheers for the request.
