### ISSUE TITLE
Ability to set multiple library folders

### ISSUE THREAD

**Issue by darrenjjeffries** [Josh5/unmanic#8]
It would be good to be able to set in the UI Multiple folders for Library. i.e. 

/mnt/user/Movies>/library/Movies
/mnt/user/Series>/library/Series

**Comment by scottcase** [comment]
It would be nice to have this ability when not using docker setup. I have this installed on a ubuntu computer that has a nvidia gpu I use for hevc encoding and would like to be able to do 
/TVShows/Kids
/TVShows/Adult
without the other directories that are in TVShows
