### ISSUE TITLE
[Feature Request] Keep Specified Language

### ISSUE THREAD

**Issue by Migz93** [Josh5/unmanic#83]
Thanks for this tool, this is great!

I was wondering if you could possibly look at adding being able to specify a certain language to keep subtitles & audio for?
So if i specify English and my file comes with foreign subs & a foreign audio track then to strip these out and leave only English?

**Comment by igoro00** [comment]
languages*

**Comment by Geek16432** [comment]
This has been a popular request on the unRaid forums for this tool.

**Comment by Josh5** [comment]
This is not going to be included with unmanic at this time. Subtitles can be a difficult  thing to manage. What happens if there is a spelling mistake, or the track does not say English. I personally think it is far better to strip subtitles out of video files.

**Comment by eihns** [comment]
is there a link for "keep only XX language/subtitles" plugin?

**Comment by Josh5** [comment]
> is there a link for "keep only XX language/subtitles" plugin?

https://github.com/Unmanic/plugin.remove_stream_by_language

**Comment by eihns** [comment]
Thats not really a solution. I would need to enter EVERY POSSIBLE combination, except the one i want. Very stupid idea.

Meanwhile i found your "Keep stream by language" plugin, which is what i want. Thanks for that.

But sometimes it fails with
