### ISSUE TITLE
[Feature request] Clear logs.

### ISSUE THREAD

**Issue by HenkaN94** [Josh5/unmanic#87]
Ability to clear specific logs, for example all succeeded, all failed or just specific entries.

To me it's not that important to save (currently 8483) failed attempts, but i'd like to keep the succeeded ones. As you can imagine it just slows things down and it's not important to keep saved in the long run.

**Comment by Geek16432** [comment]
+1 Please

**Comment by dmz94** [comment]
+1, yes please...

**Comment by my95z34** [comment]
+1, I'm currently at 21,467 failures, which makes the "History" tab completely unusable.

**Comment by Josh5** [comment]
I've modified the completed tasks table. You can now delete tasks from your history. I have removed the filter for success and failed. It is intended to readd this feature later on. For now you can sort the lists by status.

**Comment by dmz94** [comment]
Thanks for this!

**Comment by Josh5** [comment]
No problem. The history page is now paginating server side. It's should hopefully load a lot faster with thousands of entries in the history
