### ISSUE TITLE
Additonal ffmpeg settings

### ISSUE THREAD

**Issue by Zeusy123** [Josh5/unmanic#88]
Hi there, I would like to use your script, but just wondering if i can make it execute my own ffmpeg command on each video file?

example  ` -crf 23 -level 3.1 -c:a:0 libfdk_aac`

As u see i use fdkaac in my encoding and would need to use my own ffmpeg with fdk included, and set crf, etc..

I loev how your script works, but could u make it so I could use my fdk acc ffmpeg file and alloow me to execute it with my own custom command?

**Comment by Josh5** [comment]
Support added with Merger Request #129
